# Please do not delete any entries of this Config.
#  --------------------------------------------------------------------------------------
# |In order to deactivate any functions please mind about these tips:                    |
# |For numbers: Set the Value to 0.                                                      |
# |For texts: Change to ''.                                                              |
# |For booleans: Set to false.                                                           |
# |For lists: Set NONE as the only value                                                 |
#  --------------------------------------------------------------------------------------
# Please read the information above the entries before modifying them

Config:

  Prefix:
    # This prefix is shown in front of the chosen plugin messages. At the end of the prefix you should reset the color codes using &r.
    # The prefix can be added to every message using %PREFIX%.
    plugin-prefix: '&c[Infinite Blocks]&r'

  # At this part of the config you can set all plugin messages except console outputs and help lists.
  Messages:

    # This message gets send to a player who has not got the permission to run a specific command.
    no-permission: '%PREFIX% &4You are not allowed to execute that command.'

    # This message gets send to a player who has reloaded the config files.
    reloaded-config: '%PREFIX% &aThe Config has been reloaded.'
    
    # This message will be sent when the item given as a parameter for /infiniteblock is invalid
    invalid-item: '%PREFIX% &4The item you specified does not exist'
    
    # This message will be sent when the player given as a parameter for /infiniteblock is invalid
    invalid-player: '%PREFIX% &4The player you specified does not exist or is not online'
    
    # This message will be sent to a player who obtains an infinite item
    # %ITEM% = lowercase name of the item, %ITEMNAME% = Customname if specified in command, otherwise same as %ITEM%
    obtained-infinite-item: '%PREFIX% &2You obtained infinite &c%ITEMNAME%'
    
    # This message will be sent to a player who gives an infinite item to another player
    # %ITEM% = lowercase default name of the item, %ITEMNAME% = Customname if specified in command, otherwise same as %ITEM%,
    # %PLAYER% = receiving players name, %DISPLAY% = receiving players display name
    handed-out-infinite-item: '%PREFIX% &2You gave infinite &c%ITEMNAME% &2to &6%PLAYER%'

    # REQUIRES VAULT
    # This message will be sent to a player when who tries to place an infinite block while not having enough balance
    # %AMOUNT% = the amount needed to place the block
    placing-failed-missing-balance: '%PREFIX% &4You do not have the required funds (&c%AMOUNT%&4) to place this block'
    
    # This message will be sent when the command /infiniteblock is used incorrectly
    infiniteblock-help: |
      %PREFIX% &4Wrong usage of &6/infiniteblock 
      &cCommand syntax: &6/infiniteblock <item> [player] [itemname]

  Settings:
    # REQUIRES VAULT
    blockUsageCost:
      # Any material not explicitly defined below will deduct the following amount
      defaultUsageCost: 0.0
      usageCostPerMaterial:
        STONE: 0.0
        OAK_LOG: 0.0

    # Lore settings for infinite blocks
    lore:
      # A list of strings to add as the lore for infinite blocks
      # %AMOUNT% = Cost to place that infinite block
      loreList:
        - '&aThis is an infinite block'
        - '&6Cost per use: &c%AMOUNT%'

      # Whether the lore shall be force updated when the block is used
      # Setting this to true will override any lore on the block, including ones added by other means
      # Setting this to false will add the lore only once and only update infinite blocks without any lore
      forceUpdate: false

  # Permissionlist:
  # infiniteblocks.reload: Permission to reload the config.
  # infiniteblocks.infiniteblock: Permission to hand out infinite blocks
  # infiniteblocks.ignoreCost: Permission to ignore vault balance deduction when using infinite blocks